// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use session pooler (port 5432) for migrations — supports IPv4 and DDL.
    // Derived from DATABASE_URL by swapping the transaction pooler port.
    url: (process.env["DATABASE_URL"] ?? "")
      .replace(":6543", ":5432")
      .replace("?pgbouncer=true", ""),
  },
});
